name:                shlack
version:             0.0.0.2
github:              "telostat/shlack"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "Copyright (c) 2021 Telostat Pte Ltd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/telostat/shlack#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-conduit
- text

library:
  source-dirs: src

executables:
  shlack:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
    - -O2
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - shlack
    - directory
    - filepath
    - optparse-applicative
    - yaml

tests:
  shlack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shlack

  shlack-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    dependencies:
    - shlack
    - doctest
